---
title: "Final Project"
author: "Ian Nel"
date: "5/6/2021"
output: 
  html_document:
    theme: paper
  github_document: default 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(MVN)
library(lavaan)
library(tidySEM)
library(semTable)
library(semPlot)
```

```{r data input}
data_raw <- read_csv(
  here::here("data", "DT-Res_synthetic.csv"),
  col_types = cols(
    Sample = col_factor(),
    Sex = col_factor(),
    Ethnicity = col_factor(),
    .default = col_double()
  )
)
str(data_raw)
```

```{r data wrangling}

data_clean <- data_raw %>%
  select(c(
    Sample, 
    DTNEW_2R:DTNew_82, 
    DTS_1:DTS_16, 
    FDSR_1:FDSR_35, 
    TDASS_1:TDASS_25, 
    DRS_1:DRS_15,
    GRIT_1:GRIT_12,
    RS_1:RS_26,
    Tanx:Bpd)) %>% 
  mutate(
    Sample = recode(Sample, "4" = "Clinical", "3" = "College", .default = "Community")
  ) %>% 
  rowwise() %>% 
  mutate(
    DTQ_tot = mean(c_across(DTNEW_2R:DTNew_82)),
    DTS_tot = mean(c_across(DTS_1:DTS_16)),
    FDSR_tot = mean(c_across(FDSR_1:FDSR_35)),
    TDASS_tot = mean(c_across(TDASS_1:TDASS_25)),
    DRS_tot = mean(c_across(DRS_1:DRS_15)),
    GRIT_tot = mean(c_across(GRIT_1:GRIT_12)),
    RS_tot = mean(c_across(DRS_1:DRS_15)),
    .before = everything(),
  ) 
str(data_clean)
  
```
```{r summary table} 
Table_1 <- data_clean %>%
  group_by(Sample) %>% 
  summarize(
    across(c(DTQ_tot:RS_tot,Tanx:Bpd), 
    list(
        Mean = ~ mean(.x, na.rm = TRUE),
        SD = ~ sd(.x, na.rm = TRUE)),
    .groups = keep
    )
  )

Table_1
```


```{r plots}

DTQ_plot <- data_clean %>%
  ggplot(aes(DTS_tot, Sample)) +
  ggridges::geom_density_ridges() +
  scale_fill_brewer(palette = 4) +
  ggtitle("Distress Tolerance Scale Scores by Sample Type")

DTQ_plot
```


```{r testing multivariate normality assumption}
vars <- data_clean %>% 
  select(DTNEW_2R:RS_26) %>% 
  as.data.frame()

mvn_result <- mvn(vars, subset = NULL, mvnTest = "mardia", covariance = TRUE, tol = 1e-25, alpha = 0.5,
  scale = FALSE, desc = TRUE, transform = "none", R = 1000,
  univariateTest = "SW",univariatePlot = "qq", multivariatePlot = FALSE,
  multivariateOutlierMethod = "quan", bc = FALSE, bcType = NULL,
  showOutliers = FALSE, showNewData = FALSE)

MVN_Test_Result <- mvn_result$multivariateNormality
```


```{r correlated factors model fit}
CF_Model <- '

DTNEG =~ DTNEW_2R + DTNEW_5R + DTNEW_10R + DTNEW_18R + DTNEW_29R + DTNEW_47R 

DTPOS =~ DTNew_53 + DTNew_58 + DTNew_61 + DTNew_63 + DTNew_64

DTS =~ DTS_1 + DTS_2 + DTS_3 + DTS_4 + DTS_5 + DTS_7r + DTS_8 + DTS_9 + DTS_10 + DTS_11 + DTS_12 + DTS_13 +         DTS_14 + DTS_16

FDSR =~ FDSR_15 + FDSR_16 + FDSR_17 + FDSR_18 + FDSR_19 + FDSR_20 + FDSR_21 + FDSR_22 + FDSR_23 + FDSR_24 +          FDSR_25 + FDSR_26 + FDSR_27 + FDSR_28 + FDSR_29 + FDSR_30 + FDSR_31 + FDSR_32 + FDSR_33 + FDSR_34 +          FDSR_35

TDASS =~ TDASS_1 + TDASS_2 + TDASS_3 + TDASS_4 + TDASS_5 + TDASS_6 + TDASS_7 + TDASS_8 + TDASS_9 + TDASS_10 +         TDASS_11 + TDASS_12 + TDASS_13 + TDASS_14 + TDASS_15 + TDASS_16 + TDASS_17 + TDASS_18 + TDASS_19 +           TDASS_20 + TDASS_21 + TDASS_22 + TDASS_23 + TDASS_24 + TDASS_25

DRS =~  DRS_1 + DRS_2 + DRS_3r + DRS_4r + DRS_5 + DRS_6 + DRS_7 + DRS_8r + DRS_9 + DRS_10 + DRS_11r + DRS_12         + DRS_13r + DRS_14r + DRS_15

GRIT =~ GRIT_1 + GRIT_4 + GRIT_6 + GRIT_9 + GRIT_10 + GRIT_12

RS =~ RS_1 + RS_2 + RS_3 + RS_4 + RS_5 + RS_6 + RS_7 + RS_8 + RS_9 + RS_10 + RS_11 + RS_12 + RS_13 + RS_14 +       RS_15 + RS_16 + RS_17 + RS_18 + RS_19 + RS_20 + RS_21 + RS_22 + RS_23 + RS_24 + RS_25 + RS_26

Distress Tolerance =~ DTNEG + DTPOS + DTS + FDSR + TDASS 
Resilience =~ DRS + GRIT + RS'

data_clean_NonClinical <- data_clean %>% 
  filter(Sample != "Clinical")

CF_Model_Fit <- cfa(CF_Model, data = data_clean_NonClinical, estimator = "ML", missing = "fiml", std.lv= TRUE)

CF_Model_Fit_Summary <- summary(CF_Model_Fit, standardized=TRUE, fit.measures=TRUE)
CF_Model_Fit_Summary 
```

```{r CF Model Diagram}

CF_Model_Graph <- semPaths(CF_Model_Fit, whatLabels = "std", intercepts = FALSE, layout = "tree2", edge.color = "black")
title("Correlated Factors Model of Distress Tolerance and Resilience")

```

```{r exporting table}
CF_Model_Table <- semTable(
CF_Model_Fit, file = "Correlated Factors Model of Distress Tolerance and Resilience", paramSets = c("loadings", "fits"), paramSetLabels = c("loadings"= "Factor Loadings", "fits" = "Fit Indices"), columns = c(est = "Estimate", se = "SE", p = "p", "eststars" = "Significance"), fits = c("npar", "fmin", "chisq", "df", "pvalue", "baseline.chisq", "baseline.df", "baseline.pvalue", "cfi", "tli", "aic", "bic", "ntotal", "rmsea", "rmsea.ci.lower", "rmsea.ci.upper", "rmsea.pvalue", "srmr"), fitLabels = NULL, type = "latex", print.results = FALSE, alpha = c(0.05, 0.01, 0.001)
)
```


```{r file output}
write_csv(
  data_clean,
  here::here("data", "DT-Res_synthetic_clean")
)

write_csv(
  Table_1,
  here::here("output", "Distress-Tolerance_Reslience_Table")
)

ggsave(here::here("output", "DTQ_plot.png"), DTQ_plot)

write_csv(
  MVN_Test_Result,
  here::here("output", "Multivariate_Normality_Test)
  )
  
CF_Model_Graph
CF_Model_Table

ggplot(here::here,
```
```
